<center> <font color = #82318E size = 5 face = "微软雅黑" > Vorticity For Global Shallow Water  Wave</font> </center>

In [1]:
import math
import numpy as np

<center> <font color = #82318E size = 4 face = "微软雅黑" > 1. Prepare Virtual Data </font> </center>

In [55]:
im = 9

np.random.seed(522)
temp = list(map(lambda theta, phi: [math.cos(theta) * math.cos(phi), 
                                    math.cos(theta) * math.sin(phi), 
                                    math.sin(theta)],
                np.random.uniform(low = -np.pi, high = np.pi, size = im),
                np.random.uniform(low = 0, high = 2 * np.pi,  size = im)))

print(type(temp), len(temp))
print(type(temp[0]), len(temp[0]))

x = CartCoor[::, 0]; y = CartCoor[::, 1]; z = CartCoor[::, 2]

np.random.seed(522)
U = np.random.uniform(low = -5, high = 5, size = (im, 3))

np.random.seed(522)
H = np.random.uniform(low = -10, high = 10, size = (im, 1))

np.random.seed(522)
f = np.random.uniform(low = -1e-4, high = 1e-4, size = (im, 1))

<class 'list'> 9
<class 'list'> 3


<center> <font color = #82318E size = 4 face = "微软雅黑" > 2. Calculate Distance </font> </center>

In [48]:
DistMatrix = 4 * np.ones((im, im))
for i in np.arange(im):
    for j in np.arange(im):
        if j == i:
            continue
        DistMatrix[i, j] = (x[i] - x[j]) ** 2 + (y[i] - y[j]) ** 2 + (z[i] - z[j]) ** 2
    
print(DistMatrix)

print(np.argmax(DistMatrix, axis = 0))
index = np.argmin(DistMatrix, axis = 0)
print(index)

[[ 4.          3.13082045  0.66595331  2.2477717   0.58426401  2.23665088
   3.90556785  3.97845656  1.0408933 ]
 [ 3.13082045  4.          3.20470718  3.18940743  3.30140887  3.46181886
   1.01850457  0.99224477  3.93105115]
 [ 0.66595331  3.20470718  4.          0.92258383  1.77399727  1.94085526
   3.65248674  3.46324984  0.55729617]
 [ 2.2477717   3.18940743  0.92258383  4.          2.42426309  0.67145562
   2.01523746  1.79709995  0.47520487]
 [ 0.58426401  3.30140887  1.77399727  2.42426309  4.          1.29373871
   2.93344399  3.19380561  1.12553924]
 [ 2.23665088  3.46181886  1.94085526  0.67145562  1.29373871  4.
   1.52821734  1.57748116  0.59600929]
 [ 3.90556785  1.01850457  3.65248674  2.01523746  2.93344399  1.52821734
   4.          0.02963207  2.96346571]
 [ 3.97845656  0.99224477  3.46324984  1.79709995  3.19380561  1.57748116
   0.02963207  4.          2.89998113]
 [ 1.0408933   3.93105115  0.55729617  0.47520487  1.12553924  0.59600929
   2.96346571  2.89998113  4. 

In [58]:
Partial_vx = np.zeros((im, 1)) 
Partial_uy = np.zeros((im, 1))
Vorticity = np.zeros((im, 1))

for i in np.arange(im):
    Partial_vx[i, 0] = (U[i, 1] - U[index[i], 1])/(x[i] - x[index[i]])
    Partial_uy[i, 0] = (U[i, 0] - U[index[i], 0])/(y[i] - y[index[i]])

Vorticity = (f + Partial_vx - Partial_uy)/H

print(Vorticity.shape)
print(Vorticity)

(9, 1)
[[-1.23622924]
 [-0.08283105]
 [-3.81979074]
 [-1.43136013]
 [-2.53196815]
 [-3.80764208]
 [ 4.08284327]
 [ 3.62339847]
 [ 0.0660357 ]]


<center> <font color = #82318E size = 4 face = "微软雅黑" > 3. Other things </font> </center>

In [43]:
CartCoor = np.array(temp, dtype = np.float)

def cart2sph(a, b, c):
    ab = a**2 + b**2
    r = np.sqrt(ab + c**2)            # radius
    elev = np.arctan2(c, np.sqrt(ab)) # elevation
    az = np.arctan2(b, a)             # azimuth

    return az, elev, r

SphCoor = np.zeros(CartCoor.shape)
for i in np.arange(im):
    SphCoor[i, ::] = cart2sph(CartCoor[i, 0], CartCoor[i, 1], CartCoor[i, 2])
    
print(SphCoor[0:5:1, ::])

np.random.seed(522)
print(np.random.uniform(low = 0, high = 2 * np.pi,  size = im)[0:5:1].reshape(-1,1))
np.random.seed(522)
print(np.random.uniform(low = -np.pi, high = np.pi, size = im)[0:5:1].reshape(-1,1))

[[-2.97784405 -1.53197359  1.        ]
 [-0.80724224  0.57936041  1.        ]
 [ 1.1464394  -0.75221934  1.        ]
 [ 1.68503772  0.12237668  1.        ]
 [-2.84896451 -0.74798666  1.        ]]
[[ 1.60961906]
 [ 5.70382489]
 [ 2.38937331]
 [ 3.26396934]
 [ 2.393606  ]]
[[-1.53197359]
 [ 2.56223224]
 [-0.75221934]
 [ 0.12237668]
 [-0.74798666]]


In [73]:
import tensorflow as tf
'''
help(tf.constant)'''
a = tf.constant([[2, 3], [2, 3]])
print(a[1, 0])

Tensor("strided_slice_4:0", shape=(), dtype=int32)


In [75]:
help(tf.zeros)
tf.zeros((5,3))

Help on function zeros in module tensorflow.python.ops.array_ops:

zeros(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to zero.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to zero.
    
    For example:
    
    ```python
    tf.zeros([3, 4], tf.int32) ==> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
    ```
    
    Args:
      shape: Either a list of integers, or a 1-D `Tensor` of type `int32`.
      dtype: The type of an element in the resulting `Tensor`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` with all elements set to zero.



<tf.Tensor 'zeros:0' shape=(5, 3) dtype=float32>